// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnyctmaskjjezmciwbsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZueWN0bWFza2pqZXptY2l3YnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5MjM2MDAsImV4cCI6MjA1MjQ5OTYwMH0.bqbi48q1YWFz2S-BjA_RclLe2zMvLoIAomgau-iSHGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);